services:
  app:
    build: .
    container_name: mon-app-python
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - hf_cache:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_OFFLINE=1
    restart: unless-stopped

volumes:
  hf_cache: