"""schema initial : users et conversations

Revision ID: 1f8ce6099346
Revises: 
Create Date: 2026-07-14 17:30:16.437844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8ce6099346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_firstname', sa.String(length=100), nullable=False),
    sa.Column('user_surname', sa.String(length=100), nullable=False),
    sa.Column('user_mail', sa.String(length=150), nullable=False),
    sa.Column('user_pwd', sa.String(length=255), nullable=False),
    sa.Column('user_permissions', sa.Integer(), nullable=False),
    sa.Column('first_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme', sa.String(length=5), nullable=False),
    sa.Column('user_picture', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_mail')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
