"""user_pwd nullable pour les comptes OAuth

Revision ID: 344c99caa371
Revises: fec317213eee
Create Date: 2026-07-27 17:57:18.739992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344c99caa371'
down_revision = 'fec317213eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_pwd',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_pwd',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
