"""quota journalier par utilisateur

Revision ID: 96291afd3916
Revises: 809142aa9d20
Create Date: 2026-07-18 16:55:11.765920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96291afd3916'
down_revision = '809142aa9d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_daily', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('quota_daily')

    # ### end Alembic commands ###
