"""fournisseur declare sur les cles du pool

Le prefixe du secret ne suffit plus : les cles Mistral sont opaques. Nullable,
donc les cles deja en base restent reconnues comme avant.

Revision ID: cb1824b0b1b5
Revises: cb436cf47974
Create Date: 2026-09-02 22:40:18.578512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1824b0b1b5'
down_revision = 'cb436cf47974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groq_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groq_keys', schema=None) as batch_op:
        batch_op.drop_column('fournisseur')

    # ### end Alembic commands ###
