"""journal d'usage : queries et retrieval_events

Revision ID: f89380301857
Revises: 1f8ce6099346
Create Date: 2026-07-14 17:53:49.533528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89380301857'
down_revision = '1f8ce6099346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_user_id'), ['user_id'], unique=False)

    op.create_table('retrieval_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('retrieval_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_events_point_id'), ['point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_events_query_id'), ['query_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_events_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieval_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_events_query_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_events_point_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_events_created_at'))

    op.drop_table('retrieval_events')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_queries_created_at'))

    op.drop_table('queries')
    # ### end Alembic commands ###
