"""pool de cles groq remplace acces API entrant

Revision ID: fec317213eee
Revises: a752c67cb9b3
Create Date: 2026-07-18 17:43:59.196820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fec317213eee'
down_revision = 'a752c67cb9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groq_keys',
    sa.Column('groq_key_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('secret', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('groq_key_id')
    )
    # D'abord détacher queries de api_keys (retrait de la FK et de la colonne),
    # sinon DROP TABLE api_keys échoue : la contrainte y fait encore référence.
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groq_key_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_queries_api_key_id'))
        batch_op.create_index(batch_op.f('ix_queries_groq_key_id'), ['groq_key_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_queries_api_key_id_api_keys'), type_='foreignkey')
        batch_op.create_foreign_key('fk_queries_groq_key_id_groq_keys', 'groq_keys', ['groq_key_id'], ['groq_key_id'])
        batch_op.drop_column('api_key_id')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_queries_groq_key_id_groq_keys', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_queries_api_key_id_api_keys'), 'api_keys', ['api_key_id'], ['api_key_id'])
        batch_op.drop_index(batch_op.f('ix_queries_groq_key_id'))
        batch_op.create_index(batch_op.f('ix_queries_api_key_id'), ['api_key_id'], unique=False)
        batch_op.drop_column('groq_key_id')

    op.create_table('api_keys',
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quota_daily', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('api_keys_created_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('api_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('api_key_id', name=op.f('api_keys_pkey'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.drop_table('groq_keys')
    # ### end Alembic commands ###
